version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    restart: always
    expose:
      - 9000  # PHP-FPM 用ポート（Nginxが接続）
    command: php-fpm

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: youtube_scheduler
      MYSQL_USER: unicharisu
      MYSQL_PASSWORD: unipass&11ne
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

  node:
    image: node:18
    container_name: react_node
    working_dir: /app
    volumes:
      - ./:/app
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always