version: '3.8'

services:
  app:
    build:
      context: ./laravel
    container_name: laravel
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    depends_on:
      - mysql
    restart: always
    expose:
      - 9000
    command: php-fpm

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: youtube_scheduler
      MYSQL_USER: unicharisu
      MYSQL_PASSWORD: unipass&11ne
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  node:
    image: node:18
    container_name: react_node
    working_dir: /app
    volumes:
      - ./react:/app
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel/public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: always